"use server"

import { cloudinary } from "@/lib/cloudinary"
import { prisma } from "@/lib/prisma"
import { requireAuth } from "@/lib/session"
import { revalidatePath } from "next/cache"
import { EmployeeDocumentType } from "@prisma/client"

export async function uploadEmployeeDocument(
  employeeId: string,
  formData: FormData
) {
  const session = await requireAuth()
  
  // Basic authorization: user must be HR/ADMIN, or they must be the employee themselves
  if (session.role === "ENGINEER" || session.role === "LEAD") {
    const employee = await prisma.employee.findUnique({
      where: { id: employeeId },
      select: { userId: true }
    })
    if (employee?.userId !== session.userId) {
      throw new Error("Unauthorized: You can only upload your own documents.")
    }
  }

  const file = formData.get("file") as File
  const title = formData.get("title") as string
  const documentType = formData.get("documentType") as EmployeeDocumentType

  if (!file || !title || !documentType) {
    throw new Error("Missing required fields (file, title, documentType).")
  }

  // Convert File to ArrayBuffer and then to Buffer (so Cloudinary can upload it)
  const arrayBuffer = await file.arrayBuffer()
  const buffer = Buffer.from(arrayBuffer)

  // Upload to Cloudinary using a Promise wrapper around upload_stream
  const uploadResult = await new Promise<any>((resolve, reject) => {
    const uploadStream = cloudinary.uploader.upload_stream(
      {
        folder: `buildorbit/employees/${employeeId}`,
        resource_type: "auto", // Allows PDFs, Images, etc.
      },
      (error, result) => {
        if (error) return reject(error)
        resolve(result)
      }
    )
    uploadStream.end(buffer)
  })

  // Save the metadata to our database
  await prisma.employeeDocument.create({
    data: {
      employeeId,
      documentType,
      title,
      originalFilename: file.name,
      storageKey: uploadResult.secure_url, // URL generated by Cloudinary
      mimeType: file.type || "application/octet-stream",
      sizeBytes: file.size,
      uploadedById: session.userId,
    }
  })

  revalidatePath("/profile")
  revalidatePath(`/workforce/employees/${employeeId}`)
  
  return { success: true, url: uploadResult.secure_url }
}

export async function deleteEmployeeDocument(documentId: string) {
  const session = await requireAuth()
  
  const doc = await prisma.employeeDocument.findUnique({
    where: { id: documentId },
    include: { employee: true }
  })
  
  if (!doc) throw new Error("Document not found")

  if (session.role === "ENGINEER" || session.role === "LEAD") {
    if (doc.employee.userId !== session.userId) {
      throw new Error("Unauthorized")
    }
  }

  // To delete from Cloudinary, we need the public_id, which we can extract from the secure_url
  // Example URL: https://res.cloudinary.com/demo/image/upload/v12345/buildorbit/employees/xyz/doc.pdf
  // The public_id is everything after the version folder, without the file extension if it's an image.
  // A safer way if you just store secure_url is to use regex or store public_id directly.
  // Since we stored secure_url, we will do a rough extraction or skip Cloudinary deletion for now 
  // (In production, it's better to store public_id in storageKey, but we'll extract it here):
  
  try {
    const urlParts = doc.storageKey.split('/')
    const fileWithExt = urlParts.pop() // e.g. "doc.pdf"
    const publicIdWithExt = urlParts.slice(urlParts.indexOf('buildorbit')).join('/') + '/' + fileWithExt
    const publicId = publicIdWithExt.replace(/\.[^/.]+$/, "") // remove extension

    await cloudinary.uploader.destroy(publicId)
  } catch (e) {
    console.error("Failed to delete from Cloudinary", e)
  }

  await prisma.employeeDocument.delete({ where: { id: documentId } })

  revalidatePath("/profile")
  revalidatePath(`/workforce/employees/${doc.employeeId}`)
}
